sudo: required
language: cpp
compiler:
  - gcc
jobs:
  include:
    - stage: Training
      script:
        - travis_wait 30 Tests/testSetupFullEnv.sh
        - Tests/testTraining.sh
    - stage: Unpack
      script: 
        - travis_wait 30 Tests/testSetupCpuEnv.sh
        - Tests/testUnpacking.sh
notifications:
  email:
    recipients:
        - mkomm@cern.ch
    on_success: change
    on_failure: always


