sudo: required
language: cpp
compiler:
  - gcc
jobs:
  include:
    - stage: Env
      script: 
        - travis_wait 30 Tests/testSetupCpuEnv.sh
    
notifications:
  email:
    recipients:
        - mkomm@cern.ch
    on_success: change
    on_failure: always


